### ISSUE TITLE
web tidak auto read data

### ISSUE THREAD

**Issue by rezziqbal06** [agusibrahim/QRCode-Web-Scanner#1]
Mas Agus terimakasih telah membuat open source code ini. Saya ada kendala.
Ketika saya mengirim data ke firebase dengan random value yg jadi dokumennya, data berhasil masuk ke database, tapi disisi webnya engga otomatis read si datanya. Kira kira apa solusinya mas?

**Comment by agusibrahim** [comment]
Udh bisa kah?
